### ISSUE TITLE
Optuna logs all hyperparameter tuning runs to the same experiment in Weights and Biases logger--pytorch-lightning

### ISSUE THREAD

**Issue by 00krishna** [optuna/optuna-examples#29] opened 2021-06-17 21:52 UTC
## Expected behavior

I am using Optuna for hyperparameter tuning, along with Weights and Biases for logging, and Pytorch-Lightning. The tuning is working, but the problem is logging the results of the tuning trials. I would expect that for each trial--or combination of hyperparameters, that Optuna would generate a new experiment for the logger to log. Then I could look at the metrics by different experiment/combination of hyperparameters, and figure out which one works best. 

Instead, Optuna does not seem to initiate a new experiment in the logger on each training run. So what I have is that all of the hyperparameter tuning runs are getting combined into a single experiment in Weights and Biases and it looks like a mess. So I a not sure if it is just a configuration issue on my part or something else. But I was hoping that someone might know the right thing to do. 

## Environment

- Optuna version: 2.8.0
- Python version: 3.8
- OS:Ubuntu linux 20.04.2
- (Optional) Other libraries and their versions:
  - pytorch 1.9
  - pytorch-lightning: 1.3.5 

## Error messages, stack traces, or logs

No error messages are generated.

## Steps to reproduce

1. load module
2. run module.

## Reproducible examples (optional)

```python
def objective(trial: optuna.trial.Trial) -> float:

    input_window_size = trial.suggest_categorical("input_window_size", [20, 30, 40])
    output_window_size = trial.suggest_categorical("output_window_size", [ 20, 30, 40])
    test_percentage = 0.20
    val_percentage = 0.20
    lags = [1, 2, 3, 365, 366, 367]
    lag_combos = list(powerset(lags))
    laglist = trial.suggest_categorical("lags", lag_combos)
    drop_columns = ['pr', 'tmmx']
    drop_column_combos = list(powerset(drop_columns))
    remove_columns = trial.suggest_categorical("remove_columns", drop_column_combos)
    batch_size = trial.suggest_categorical("batch_size",[16, 32, 64, 128])
        
    datamodule = get_dataset('Sensor1') 
    datamodule = datamodule(input_window_size=input_window_size,
                            output_window_size=output_window_size,
                            test_percentage=test_percentage,
                            val_percentage=val_percentage,
                            laglist=laglist,
                            remove_columns=remove_columns,
                            batch_size=batch_size)
    
    datamodule.prepare_data()
    datamodule.setup()


    hidden_dim = trial.suggest_categorical("hidden_dim", [16, 32, 64, 128])
    num_layers = trial.suggest_int("num_layers", 1, 3)
    dropout = trial.suggest_float("dropout", 0.2, 0.5, step=0.1)

    optimizer_name = trial.suggest_categorical("optimizer", ["Adam", "RMSprop", "SGD"])
    lr = trial.suggest_uniform("lr", 1e-5, 1e-1)

    model = LitDivSensor(num_features = datamodule.num_features,
                            hidden_dim = hidden_dim,
                            num_layers = num_layers,
                            dropout = dropout,
                            debug = False,
                            learning_rate = lr,
                            batch_size = batch_size,
                            optimizer_name=optimizer_name)

    tb_logger = pl_loggers.TensorBoardLogger('logs/', name='division-bell-rnn')
    wandb_logger = pl_loggers.WandbLogger(name='division-bell-rnn'+ str(date_time),  ## NOTE WANDB LOGGER 
                                          save_dir='logs/', 
                                          project='division-bell', 
                                          entity='kwater',
                                          offline=False)
    trainer = pl.Trainer(
        logger=[tb_logger, wandb_logger],
        checkpoint_callback=False,
        max_epochs=EPOCHS,
        gpus=1 if torch.cuda.is_available() else None,
        callbacks=[PyTorchLightningPruningCallback(trial, monitor="val_loss")])

    hyperparameters = dict(input_window_size=input_window_size, 
                           output_window_size=output_window_size,
                           laglist=laglist,
                           remove_columns=remove_columns,
                           batch_size = batch_size,
                           hidden_dim=hidden_dim,
                           num_layers=num_layers,
                           dropout=dropout,
                           optimizer_name=optimizer_name,
                           learning_rate=lr)

    trainer.logger.log_hyperparams(hyperparameters)
    trainer.fit(model, datamodule=datamodule)

    return trainer.callback_metrics["val_loss"].item()

if __name__ == "__main__":
    pruner: optuna.pruners.BasePruner = (
            optuna.pruners.MedianPruner())

    study = optuna.create_study(direction="minimize", pruner=pruner)
    study.optimize(objective, n_trials=3, timeout=600)

```

## Additional context (optional)

Here is a picture of the loggers where you can see all of the hyperparameter losses are in the same experiment--and hence under the same color line. the green line is from a previous experiment. 

![DeepinScreenshot_select-area_20210617174415](https://user-images.githubusercontent.com/2063593/122476755-b42eaf80-cf94-11eb-988c-4253639a7451.png)

**Comment by nzw0301** [comment] 2021-06-25 15:41
I'm not familiar with wandb and the code is not reproducible, but I suppose `name` of `WandbLogger ` should have a different name depending on the trial id. What do you think about it?

**Comment by nzw0301** [comment] 2021-07-06 16:17
Sorry, my previous answer was incorrect. I think the purple line represents only one trial since `name` depends on `date_time`. So I think that the reason is the configuration issue or only one trial is done during optimisation because of timeout.

Thus let me close the issue.

**Closed by nzw0301** 2021-07-06 16:17 UTC
Labels: question
